entryPoints:
  web:
    address: ":80"   # HTTP entry point (this will not be used anymore)
  websecure:
    address: ":443"  # HTTPS entry point (this will be used for all traffic)

certificatesResolvers:
  myresolver:
    acme:
      email: "you@saydao.org"
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web  # This will be used for the HTTP challenge (on port 80), required for certificate issuance
